# -*- coding: utf-8 -*-

# Form implementation generated from reading design file 'data/add_quote.design'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.formLayout_2 = QtWidgets.QFormLayout(Form)
        self.formLayout_2.setObjectName("formLayout_2")
        self.isAuthorLabel = QtWidgets.QLabel(Form)
        self.isAuthorLabel.setObjectName("isAuthorLabel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.isAuthorLabel)
        self.isAuthorCheckbox = QtWidgets.QCheckBox(Form)
        self.isAuthorCheckbox.setText("")
        self.isAuthorCheckbox.setObjectName("isAuthorCheckbox")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.isAuthorCheckbox)
        self.chooseAuthorLabel = QtWidgets.QLabel(Form)
        self.chooseAuthorLabel.setObjectName("chooseAuthorLabel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.chooseAuthorLabel)
        self.chooseAuthorComboBox = QtWidgets.QComboBox(Form)
        self.chooseAuthorComboBox.setObjectName("chooseAuthorComboBox")
        self.chooseAuthorComboBox.addItem("")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.chooseAuthorComboBox)
        self.authorLabel = QtWidgets.QLabel(Form)
        self.authorLabel.setObjectName("authorLabel")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.authorLabel)
        self.nameLineEdit = QtWidgets.QLineEdit(Form)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.nameLineEdit)
        self.birthdayLabel = QtWidgets.QLabel(Form)
        self.birthdayLabel.setObjectName("birthdayLabel")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.birthdayLabel)
        self.birthdayDateEdit = QtWidgets.QDateEdit(Form)
        self.birthdayDateEdit.setObjectName("birthdayDateEdit")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.birthdayDateEdit)
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.imageLabel = QtWidgets.QLabel(Form)
        self.imageLabel.setText("")
        self.imageLabel.setObjectName("imageLabel")
        self.verticalLayout.addWidget(self.imageLabel)
        self.imagePushButton = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imagePushButton.sizePolicy().hasHeightForWidth())
        self.imagePushButton.setSizePolicy(sizePolicy)
        self.imagePushButton.setObjectName("imagePushButton")
        self.verticalLayout.addWidget(self.imagePushButton)
        self.formLayout_2.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.verticalLayout)
        self.quoteLabel = QtWidgets.QLabel(Form)
        self.quoteLabel.setObjectName("quoteLabel")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.quoteLabel)
        self.quoteTextEdit = QtWidgets.QTextEdit(Form)
        self.quoteTextEdit.setObjectName("quoteTextEdit")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.quoteTextEdit)
        self.quoteAddButton = QtWidgets.QPushButton(Form)
        self.quoteAddButton.setObjectName("quoteAddButton")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.quoteAddButton)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Add quote"))
        self.isAuthorLabel.setText(_translate("Form", "You author?"))
        self.chooseAuthorLabel.setText(_translate("Form", "Choose Author"))
        self.chooseAuthorComboBox.setItemText(0, _translate("Form", "No Author"))
        self.authorLabel.setText(_translate("Form", "New Author"))
        self.nameLineEdit.setPlaceholderText(_translate("Form", "Author Name"))
        self.birthdayLabel.setText(_translate("Form", "Birthday"))
        self.label.setText(_translate("Form", "Picture"))
        self.imagePushButton.setText(_translate("Form", "Select Image"))
        self.quoteLabel.setText(_translate("Form", "Quote"))
        self.quoteAddButton.setText(_translate("Form", "Add"))
