# -*- coding: utf-8 -*-

# Form implementation generated from reading design file 'data/sort_quotes.design'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(194, 133)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.sortByNameRadioButton = QtWidgets.QRadioButton(Form)
        self.sortByNameRadioButton.setObjectName("sortByNameRadioButton")
        self.buttonGroup = QtWidgets.QButtonGroup(Form)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.sortByNameRadioButton)
        self.verticalLayout.addWidget(self.sortByNameRadioButton)
        self.sortByQuoteRadioButton = QtWidgets.QRadioButton(Form)
        self.sortByQuoteRadioButton.setObjectName("sortByQuoteRadioButton")
        self.buttonGroup.addButton(self.sortByQuoteRadioButton)
        self.verticalLayout.addWidget(self.sortByQuoteRadioButton)
        self.sortByUserAddedRadioButton = QtWidgets.QRadioButton(Form)
        self.sortByUserAddedRadioButton.setObjectName("sortByUserAddedRadioButton")
        self.buttonGroup.addButton(self.sortByUserAddedRadioButton)
        self.verticalLayout.addWidget(self.sortByUserAddedRadioButton)
        self.reverseCheckBox = QtWidgets.QCheckBox(Form)
        self.reverseCheckBox.setObjectName("reverseCheckBox")
        self.verticalLayout.addWidget(self.reverseCheckBox)
        self.submitPushButton = QtWidgets.QPushButton(Form)
        self.submitPushButton.setObjectName("submitPushButton")
        self.verticalLayout.addWidget(self.submitPushButton)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Sort Quotes"))
        self.sortByNameRadioButton.setText(_translate("Form", "Sort by author name"))
        self.sortByQuoteRadioButton.setText(_translate("Form", "Sort by quote"))
        self.sortByUserAddedRadioButton.setText(_translate("Form", "Sort by user added"))
        self.reverseCheckBox.setText(_translate("Form", "Reverse"))
        self.submitPushButton.setText(_translate("Form", "Ok"))
